In [1]:
import numpy as np 

In [2]:
A = np.array([[1,0,1,0],[-1,2,-1,2],[3,1,3,1],[0,-1,0,-1]])

In [3]:
D = np.linalg.matrix_power(A,20)
print(D)

[[ 47804687500  18259765625  47804687500  18259765625]
 [-84324218750 -32208984375 -84324218750 -32208984375]
 [125154296875  47804687500 125154296875  47804687500]
 [ 18259765625   6974609375  18259765625   6974609375]]


In [4]:
B = np.array([[5,4],[3,-5]])
print(np.linalg.det(A))
print(np.linalg.det(B))

# ¿Qué se observa?
# Se puede observar que el determinante de la matriz A nos arroja un resultado erróneo al que debería salir.
# Ya que en realidad el determinante de la matríz A debe ser igual a 0 debido a una proposición vista en el curso:
# Si una matriz tiene dos columnas iguales entonces su determinante es 0.
# En la matriz B podemos observar que sí nos da el mismo resultado que si lo hacemos a mano pero sólo en la parte
# entera.

-6.162975822039151e-33
-37.000000000000014


In [5]:
import sympy as sp

In [6]:
A=sp.Matrix([[1,0,1,0],[-1,2,-1,2],[3,1,3,1],[0,-1,0,-1]])
B=sp.Matrix([[5,4],[3,-5]])

In [7]:
print(A.det())
print(B.det())

0
-37


In [8]:
print(A.rref())
# Podemos observar que el rango de A es 2, debido a que su forma escalonada reducida tiene 2 renglones no nulos

(Matrix([
[1, 0, 1, 0],
[0, 1, 0, 1],
[0, 0, 0, 0],
[0, 0, 0, 0]]), (0, 1))


In [9]:
C = sp.Matrix([[-2,6,6,8,-4],[7,-2,6,4,3],[-4,7,5,5,6],[5,3,-4,8,2],[6,8,6,1,9]])
b = sp.Matrix([[6],[14],[36],[40],[79]]) #Vector columna
matrices = [] #Lista para guardar las Ci
for i in range(5):
    temp = C.col_insert(i,b)
    temp.col_del(i+1)
    matrices.append(temp)
matrices

[Matrix([
 [ 6,  6,  6, 8, -4],
 [14, -2,  6, 4,  3],
 [36,  7,  5, 5,  6],
 [40,  3, -4, 8,  2],
 [79,  8,  6, 1,  9]]),
 Matrix([
 [-2,  6,  6, 8, -4],
 [ 7, 14,  6, 4,  3],
 [-4, 36,  5, 5,  6],
 [ 5, 40, -4, 8,  2],
 [ 6, 79,  6, 1,  9]]),
 Matrix([
 [-2,  6,  6, 8, -4],
 [ 7, -2, 14, 4,  3],
 [-4,  7, 36, 5,  6],
 [ 5,  3, 40, 8,  2],
 [ 6,  8, 79, 1,  9]]),
 Matrix([
 [-2,  6,  6,  6, -4],
 [ 7, -2,  6, 14,  3],
 [-4,  7,  5, 36,  6],
 [ 5,  3, -4, 40,  2],
 [ 6,  8,  6, 79,  9]]),
 Matrix([
 [-2,  6,  6, 8,  6],
 [ 7, -2,  6, 4, 14],
 [-4,  7,  5, 5, 36],
 [ 5,  3, -4, 8, 40],
 [ 6,  8,  6, 1, 79]])]

In [10]:
determinantes = []
det_c = C.det()
for m in matrices :
    d = m.det()
    determinantes.append(d)
x = []
for d in determinantes:
    xi = d/det_c
    x.append(xi)
print("Los valores de x1,...,x5 respectivamente son: ", x)

Los valores de x1,...,x5 respectivamente son:  [3, 5, -1, 0, 3]


In [11]:
T = sp.Matrix([[0,0,1],[1,0,1],[0,1,1]])
pot_t = []
for i in range(1,8):
    ti = T**i
    pot_t.append(ti)
pot_t

[Matrix([
 [0, 0, 1],
 [1, 0, 1],
 [0, 1, 1]]),
 Matrix([
 [0, 1, 1],
 [0, 1, 2],
 [1, 1, 2]]),
 Matrix([
 [1, 1, 2],
 [1, 2, 3],
 [1, 2, 4]]),
 Matrix([
 [1, 2, 4],
 [2, 3, 6],
 [2, 4, 7]]),
 Matrix([
 [2, 4,  7],
 [3, 6, 11],
 [4, 7, 13]]),
 Matrix([
 [4,  7, 13],
 [6, 11, 20],
 [7, 13, 24]]),
 Matrix([
 [ 7, 13, 24],
 [11, 20, 37],
 [13, 24, 44]])]

In [12]:
# ¿Puedes identificar a los números de la sucesión Tribonacci en las entradas estas matrices? 
# ¿Dónde? Enuncia una conjetura.

# Sí se pueden observar los números de la sucesión en las matrices, se pueden observar en la primer y última
# fila.

# Al observar muy bien las matrices podemos hacer la siguiente conjetura:
# Sea T = {0,0,1}
#         {1,0,1}
#         {0,1,1}  Y {T^1,T^2,T^3,T^4,T^5,...} las correspondientes potencias de T
# Además sean {t_1,t_2,t_3,t_4,t_5,...} los números de la sucesión de Tribonacci. 
# Entonces en general podemos decir que:

# T^n = {t_n           , t_n+1       , t_n+2}
#       {t_n+2 - t_n+1 , t_n + t_n+1 , t_n+1 + t_n+2}
#       {t_n+1         , t_n+2       , t_n+3}

# Se puede comprobar con las primeras 7 potencias de T.


# Liprandi Cortes Rodrigo
# 317275605