In [1]:
print("¡Hola Mundo!")

¡Hola Mundo!


In [2]:
x=3
y=4
print(x+y,x*y)

7 12


In [3]:
import numpy as np

In [4]:
A=np.array([[1,0,3],[0,1,-1]])
B=np.array([[4,1,0,-1],[5,-1,-8,0],[0,0,1,-2]])

In [5]:
print(A)
print(B)

[[ 1  0  3]
 [ 0  1 -1]]
[[ 4  1  0 -1]
 [ 5 -1 -8  0]
 [ 0  0  1 -2]]


In [6]:
C = np.matmul(A,B)
print("La multiplicación de \n{}\n y \n{}\n es la matriz \n{}".format(A,B,C))

La multiplicación de 
[[ 1  0  3]
 [ 0  1 -1]]
 y 
[[ 4  1  0 -1]
 [ 5 -1 -8  0]
 [ 0  0  1 -2]]
 es la matriz 
[[ 4  1  3 -7]
 [ 5 -1 -9  2]]


In [7]:
# Rodrigo Liprandi 